// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/taime-headspace/Dashboard.tsx": () => import("../components/mockups/taime-headspace/Dashboard.tsx"),
  "./components/mockups/taime-headspace/Schedule.tsx": () => import("../components/mockups/taime-headspace/Schedule.tsx"),
  "./components/mockups/taime-headspace/Team.tsx": () => import("../components/mockups/taime-headspace/Team.tsx"),
  "./components/mockups/taime-mobile/Dashboard.tsx": () => import("../components/mockups/taime-mobile/Dashboard.tsx"),
  "./components/mockups/taime-mobile/Schedule.tsx": () => import("../components/mockups/taime-mobile/Schedule.tsx"),
  "./components/mockups/taime-mobile/Team.tsx": () => import("../components/mockups/taime-mobile/Team.tsx"),
  "./components/mockups/taime-fusion/Dashboard.tsx": () => import("../components/mockups/taime-fusion/Dashboard.tsx"),
  "./components/mockups/taime-fusion/Schedule.tsx": () => import("../components/mockups/taime-fusion/Schedule.tsx"),
  "./components/mockups/taime-fusion/Team.tsx": () => import("../components/mockups/taime-fusion/Team.tsx"),
  "./components/mockups/taime-simple/DashboardV3.tsx": () => import("../components/mockups/taime-simple/DashboardV3.tsx"),
  "./components/mockups/taime-simple/SimplifiedA.tsx": () => import("../components/mockups/taime-simple/SimplifiedA.tsx"),
  "./components/mockups/taime-simple/SimplifiedB.tsx": () => import("../components/mockups/taime-simple/SimplifiedB.tsx"),
  "./components/mockups/taime-stripe/avail.tsx": () => import("../components/mockups/taime-stripe/avail.tsx"),
  "./components/mockups/taime-stripe/cash.tsx": () => import("../components/mockups/taime-stripe/cash.tsx"),
  "./components/mockups/taime-stripe/clockin.tsx": () => import("../components/mockups/taime-stripe/clockin.tsx"),
  "./components/mockups/taime-stripe/dashboard.tsx": () => import("../components/mockups/taime-stripe/dashboard.tsx"),
  "./components/mockups/taime-stripe/edit-shift.tsx": () => import("../components/mockups/taime-stripe/edit-shift.tsx"),
  "./components/mockups/taime-stripe/learning.tsx": () => import("../components/mockups/taime-stripe/learning.tsx"),
  "./components/mockups/taime-stripe/manager.tsx": () => import("../components/mockups/taime-stripe/manager.tsx"),
  "./components/mockups/taime-stripe/messages.tsx": () => import("../components/mockups/taime-stripe/messages.tsx"),
  "./components/mockups/taime-stripe/schedule.tsx": () => import("../components/mockups/taime-stripe/schedule.tsx"),
  "./components/mockups/taime-stripe/tasks.tsx": () => import("../components/mockups/taime-stripe/tasks.tsx"),
  "./components/mockups/taime-stripe/team.tsx": () => import("../components/mockups/taime-stripe/team.tsx")
};
